config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  
  resources :articles
  resources :utilisateurs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @articles = Article.find(params[:id])
  end
 
  def new
    @articles = Article.new
  end

  def create
    @articles = Article.new(article_params)

    if @articles.save
      redirect_to @articles
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def article_params
    params.require(:article).permit(
      :title,
      :body
    )
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  def index
    @utilisateurs = Utilisateur.all
  end

  def show
    @utilisateurs = Utilisateur.find(params[:id])
  end
 
  def new
    @utilisateurs = Utilisateur.new
  end

  def create
    @utilisateurs = Utilisateur.new(utilisateur_params)

    if @utilisateurs.save
      redirect_to @utilisateurs
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def utilisateur_params
    params.require(:utilisateur).permit(
      :nom,
      :prenom,
      :age,
      :adresse,
      :photo
    )
  end
  
  def edit
    @utilisateurs = Utilisateur.find_by(id: params[:id])
  end

  def update
    @utilisateurs = Utilisateur.find_by(id: params[:id])

    if @utilisateurs.update(utilisateur_params)
      flash[:notice] = "Bien modifier"
      redirect_to @utilisateurs
    else
      render :edit
    end
  end

  def delete
    @utilisateurs = Utilisateur.find(params[:id])
    @utilisateurs.destroy
    @utilisateurs = Utilisateur.all
    redirect_to "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
    <% @articles.each do |article| %>
        <li>             
           <%= link_to article.title, article %>      
        </li>
    <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

           
    <%= form_with model: @articles do |form| %>
        <div>
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>      
        <div>
            <%= form.label :body %>
            <%= form.text_field :body %>
        </div>  
        <div>
            <%= form.submit %>
        </div>
    <% end %>

app/views/articles/show.html.erb
<h1><%= @articles.title %></h1>
<p><%= @articles.body %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Devoir</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="./articles">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./utilisateurs">Utilisateurs</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/utilisateurs/edit.html.erb
<div class="container">
    <h1>Modifier Utilisateur</h1>
            
        <%= form_with model: @utilisateurs do |form| %>
            <div class="field">
                <%= form.label :nom %>
                <%= form.text_field :nom, class:"form-control" %>
            </div>      
            <div class="field">
                <%= form.label :prenom %>
                <%= form.text_field :prenom, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :age %>
                <%= form.number_field :age, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :adresse %>
                <%= form.text_field :adresse, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :photo %>
                <%= form.text_field :photo, class:"form-control" %>
            </div><br>  
            <div class="actions">
                <%= form.submit class:"btn btn-secondary"%>
            </div>
        <% end %>
</div>

app/views/utilisateurs/index.html.erb
<div class="container">
    <h1>Utilisateurs</h1>
 
    <table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prenom</th>
        <th scope="col">Age</th>
        <th scope="col">Adresse</th>
        <th scope="col">Photo</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        <% @utilisateurs.each do |utilisateur| %>
            <tr>     
                <td><%= utilisateur.nom %></td>
                <td><%= utilisateur.prenom %></td>
                <td><%= utilisateur.age %></td>
                <td><%= utilisateur.adresse %></td>
                <td><%= utilisateur.photo %></td>
                <td><%= link_to 'Voir profile', utilisateur, class:"btn btn-primary"%></td>
            </tr> 
        <% end %> 
    </tbody>
    </table>
    <br>
    <%= link_to "Nouveau utilisateurs", new_utilisateur_path, class:"btn btn-secondary"%>
</div>

app/views/utilisateurs/new.html.erb
<div class="container">
    <h1>Nouveau Utilisateur</h1>
            
        <%= form_with model: @utilisateurs do |form| %>
            <div class="field">
                <%= form.label :nom %>
                <%= form.text_field :nom, class:"form-control" %>
            </div>      
            <div class="field">
                <%= form.label :prenom %>
                <%= form.text_field :prenom, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :age %>
                <%= form.number_field :age, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :adresse %>
                <%= form.text_field :adresse, class:"form-control" %>
            </div>  
            <div class="field">
                <%= form.label :photo %>
                <%= form.text_field :photo, class:"form-control" %>
            </div><br>  
            <div class="actions">
                <%= form.submit class:"btn btn-secondary"%>
            </div>
        <% end %>
</div>

app/views/utilisateurs/show.html.erb
<div class="container">
    <h1>Profile</h1>
    <p>
        <strong>Nom :</strong>
        <%= @utilisateurs.nom %>
    </p>
    <p>
        <strong>Prenom :</strong>
        <%= @utilisateurs.prenom %>
    </p>
    <p>
        <strong>Age :</strong>
        <%= @utilisateurs.age %>
    </p>
    <p>
        <strong>Adresse :</strong>
        <%= @utilisateurs.adresse %>
    </p>
    <p>
        <strong>Photo :</strong>
        <%= @utilisateurs.photo %>
    </p>
    <%= link_to "Modifier", edit_utilisateur_path(@utilisateurs.id), class:"btn btn-primary"%>
    <%= link_to "Supprimer", @utilisateurs, method: :delete, data: {confirm: 'Vous etes sur de supprimer ?'}, class:"btn btn-danger"%>
    <a href="/delete/<%= @utilisateurs.id %>" data-method="delete" class="btn btn-danger">Supprimer</a>
</div>
 